### ISSUE TITLE
同时集成alipaySdk和pushSdk会类冲突

### ISSUE THREAD

**Issue by Hemumu** [aliyun/alicloud-android-demo#120]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/ta/utdid2/device/UTDevice;

**Comment by asialee** [comment]
https://help.aliyun.com/knowledge_detail/39984.html?spm=5176.7830096.2.12.aDXkg0
