### ISSUE TITLE
AlipaySdk的utdid2 与aliclud 的utdid冲突，请问如何解决，很急马上要发版本了，请帮忙看看！谢谢

### ISSUE THREAD

**Issue by 15189611** [aliyun/alicloud-android-demo#133]
Error:Execution failed for task ':YupaopaoCrop:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/ta/utdid2/a/a.class

**Comment by SducodeMonkey** [comment]
参考：https://help.aliyun.com/knowledge_detail/39984.html?spm=5176.7830096.2.11.OS6m60
另外，Github的Issue响应及时性不高，每个产品都有对应的支持群，可以加下方便及时响应，或者提对应产品的工单。
