### ISSUE TITLE
推送集成报错：PushPackage.java:25: 错误: 方法不会 覆盖或实现超类型的方法     @Override

### ISSUE THREAD

**Issue by pykui** [aliyun/alicloud-android-demo#193]
AwesomeProject\android\app\src\main\java\com\awesomeproject\push\PushPackage.java:25: 错误: 方法不会 覆盖或实现超类型的方法
    @Override
![qq 20180515170700](https://user-images.githubusercontent.com/16478496/40047568-69331dc4-5862-11e8-87d6-4ac382ddc789.png)
![qq 20180515171210](https://user-images.githubusercontent.com/16478496/40047826-2213bce0-5863-11e8-9f73-d73e7da375c5.png)

**Comment by pykui** [comment]
问题已解决

**Comment by roy2651** [comment]
请问这个是怎么解决的
