### ISSUE TITLE
Android阿里推送SDK和百川SDK依赖冲突

### ISSUE THREAD

**Issue by katana000** [aliyun/alicloud-android-demo#233]
你好：

推送SDK：com.aliyun.ams:alicloud-android-push:3.1.10
百川SDK：4.9.2.4

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.alibaba.mtl.appmonitor.AppMonitor found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$1 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$2 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$3 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$4 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$5 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$6 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$7 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$8 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$9 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Alarm found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Alarm$1 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Alarm$2 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Alarm$3 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Alarm$4 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Alarm$5 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Alarm$6 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Counter found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Counter$1 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Counter$2 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Counter$3 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Counter$4 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$OffLineCounter found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Stat found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Stat$1 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Stat$2 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Stat$3 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Stat$4 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Stat$5 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitor$Stat$6 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.AppMonitorStatTable found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.Transaction found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.Transaction$1 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.Dimension found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.Dimension$1 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.DimensionSet found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.DimensionSet$1 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.DimensionValueSet found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.DimensionValueSet$1 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.Measure found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.Measure$1 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.MeasureSet found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.MeasureSet$1 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.MeasureValue found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.MeasureValue$1 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.MeasureValueSet found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.alibaba.mtl.appmonitor.model.MeasureValueSet$1 found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ta.utdid2.device.UTDevice found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-utdid-1.5.2.jar (com.aliyun.ams:alicloud-android-utdid:1.5.2)
  Duplicate class com.taobao.a.a.a found in modules jetified-alibctriver-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctriver:4.9.2.4) and jetified-alicloud-android-push-3.1.10-runtime.jar (com.aliyun.ams:alicloud-android-push:3.1.10)
  Duplicate class com.taobao.statistic.TBS found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.device.AidCallback found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-utdid-1.5.2.jar (com.aliyun.ams:alicloud-android-utdid:1.5.2)
  Duplicate class com.ut.device.AidConstants found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-utdid-1.5.2.jar (com.aliyun.ams:alicloud-android-utdid:1.5.2)
  Duplicate class com.ut.device.UTDevice found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-utdid-1.5.2.jar (com.aliyun.ams:alicloud-android-utdid:1.5.2)
  Duplicate class com.ut.mini.IUTApplication found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.IUTPageTrack found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.UTAnalytics found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.UTHitBuilders found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.UTHitBuilders$UTControlHitBuilder found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.UTHitBuilders$UTCustomHitBuilder found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.UTHitBuilders$UTHitBuilder found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.UTHitBuilders$UTPageHitBuilder found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.UTHybridHelper found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.UTPageHitHelper found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.UTPageHitHelper$UTPageEventObject found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.UTPageStatus found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.UTTracker found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.core.sign.IUTRequestAuthentication found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.core.sign.UTBaseRequestAuthentication found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.core.sign.UTSecuritySDKRequestAuthentication found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.crashhandler.IUTCrashCaughtListner found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.internal.UTOriginalCustomHitBuilder found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)
  Duplicate class com.ut.mini.internal.UTTeamWork found in modules jetified-alibctradecommon-4.9.2.4-runtime.jar (com.alibaba.baichuan.sdk:alibctradecommon:4.9.2.4) and jetified-alicloud-android-ut-5.4.3.jar (com.aliyun.ams:alicloud-android-ut:5.4.3)

**Comment by SducodeMonkey** [comment]
请参考：[阿里云-云产品SDK UTDID冲突的解决方案](https://help.aliyun.com/knowledge_detail/39984.html)

**Comment by new-xd** [comment]
这个问题比较特殊，具体取决于两个sdk的一些底层库实现版本， 如果目前还没有解决，请进钉钉技术支持群 30959784，咨询
