### ISSUE TITLE
阿里推送和阿里百川IM同时集成会报错

### ISSUE THREAD

**Issue by wblyuyang** [aliyun/alicloud-android-demo#81]
Error:Execution failed for task ':ipark2:transformClassesWithJarMergingForDebug'.

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/alibaba/sdk/android/BuildConfig.class

**Comment by asialee** [comment]
新版阿里推送已经剥离了oneSdk，建议重新参照集成文档集成一下：https://help.aliyun.com/document_detail/30064.html?spm=5176.product30047.6.640.jTstZI
